import { useState } from 'react';
import { 
  X, 
  Sparkles, 
  Check, 
  Edit2, 
  RefreshCw, 
  Clock, 
  MapPin, 
  DollarSign,
  Users,
  Send,
  ThumbsUp,
  ThumbsDown,
  ChevronLeft,
  ChevronRight,
  ChevronDown,
  ChevronUp
} from 'lucide-react';

interface Activity {
  id: number;
  time: string;
  title: string;
  location: string;
  duration: string;
  cost: string;
  description: string;
  category: 'food' | 'attraction' | 'transport' | 'accommodation';
}

interface Props {
  onClose: () => void;
  onAccept: (activities: Activity[]) => void;
}

const sampleActivities: Activity[] = [
  {
    id: 1,
    time: '08:00 AM',
    title: 'Breakfast at Phở 10',
    location: 'Old Quarter, Hanoi',
    duration: '1 hour',
    cost: '150,000 VND',
    description: 'Traditional Vietnamese breakfast with authentic phở',
    category: 'food'
  },
  {
    id: 2,
    time: '09:30 AM',
    title: 'Hoàn Kiếm Lake Walk',
    location: 'Hoàn Kiếm District',
    duration: '1.5 hours',
    cost: 'Free',
    description: 'Scenic walk around the iconic lake in central Hanoi',
    category: 'attraction'
  },
  {
    id: 3,
    time: '11:30 AM',
    title: 'Temple of Literature',
    location: 'Đống Đa, Hanoi',
    duration: '2 hours',
    cost: '30,000 VND',
    description: "Vietnam's first national university, rich in history",
    category: 'attraction'
  },
  {
    id: 4,
    time: '01:30 PM',
    title: 'Lunch at Bún Chả Hương Liên',
    location: 'Hai Bà Trưng, Hanoi',
    duration: '1 hour',
    cost: '200,000 VND',
    description: 'Famous spot where Obama tried bún chả',
    category: 'food'
  },
  {
    id: 5,
    time: '03:00 PM',
    title: 'Vietnamese Women Museum',
    location: 'Hoàn Kiếm, Hanoi',
    duration: '1.5 hours',
    cost: '40,000 VND',
    description: 'Explore Vietnamese culture and women\'s history',
    category: 'attraction'
  },
  {
    id: 6,
    time: '05:00 PM',
    title: 'Coffee at The Hanoi Social Club',
    location: 'Hoàn Kiếm, Hanoi',
    duration: '1 hour',
    cost: '100,000 VND',
    description: 'Relax with Vietnamese coffee in a cozy atmosphere',
    category: 'food'
  }
];

const categoryColors = {
  food: 'bg-orange-500',
  attraction: 'bg-blue-500',
  transport: 'bg-green-500',
  accommodation: 'bg-purple-500'
};

const categoryEmoji = {
  food: '🍜',
  attraction: '🏛️',
  transport: '🚗',
  accommodation: '🏨'
};

export function AITripPlanner({ onClose, onAccept }: Props) {
  const [activities, setActivities] = useState<Activity[]>(sampleActivities);
  const [selectedActivity, setSelectedActivity] = useState<Activity | null>(null);
  const [editingId, setEditingId] = useState<number | null>(null);
  const [aiPrompt, setAiPrompt] = useState('');
  const [scrollPosition, setScrollPosition] = useState(0);
  const [showAIInput, setShowAIInput] = useState(true);
  
  // Thêm state loading để hiển thị hiệu ứng khi gọi API
  const [isProcessing, setIsProcessing] = useState(false);

  const handleAcceptAll = () => {
    onAccept(activities);
    onClose();
  };

  const handleRegenerateActivity = (id: number) => {
    // Simulate AI regeneration
    setActivities(activities.map(a => 
      a.id === id 
        ? { ...a, title: a.title + ' (Updated)', description: a.description + ' - Regenerated by AI' }
        : a
    ));
  };

  // --- HÀM HELPER ĐỂ CHUYỂN ĐỔI INTENT TỪ SERVER SANG CATEGORY CỦA UI ---
  const mapIntentToCategory = (intent: string): Activity['category'] => {
    const i = intent.toLowerCase();
    if (i.includes('ăn') || i.includes('uống') || i.includes('phở') || i.includes('nhà hàng') || i.includes('cafe')) return 'food';
    if (i.includes('xe') || i.includes('ga') || i.includes('sân bay')) return 'transport';
    if (i.includes('khách sạn') || i.includes('nghỉ') || i.includes('homestay')) return 'accommodation';
    return 'attraction'; // Mặc định
  };

  // --- HÀM GỌI API THẬT (Thay thế hàm console.log cũ) ---
  const handleSendPrompt = async () => {
    if (!aiPrompt.trim()) return;

    setIsProcessing(true); // Bật loading
    try {
      // Gọi xuống server Python (Cổng 5000)
      const response = await fetch('http://127.0.0.1:5000/api/chat', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ message: aiPrompt }),
      });

      const data = await response.json();

      if (data.status === 'success') {
        // Map dữ liệu từ Python (Vietmap) sang format Activity của giao diện
        const newActivities: Activity[] = data.data.map((item: any, index: number) => ({
          id: Date.now() + index,
          time: 'TBD', // Python chưa trả về giờ, tạm để TBD
          title: item.name || item.step_intent,
          location: item.address || 'Vietnam',
          duration: '1-2 hours',
          cost: 'Varies',
          description: `Gợi ý từ AI: ${item.step_intent}`,
          category: mapIntentToCategory(item.step_intent),
        }));

        setActivities(newActivities); // Cập nhật danh sách hoạt động mới
      } else {
        alert("AI không trả về kết quả hợp lệ.");
      }
    } catch (error) {
      console.error('Error calling AI:', error);
      alert("Lỗi kết nối tới Server AI (Kiểm tra lại xem đã chạy python run.py chưa)");
    } finally {
      setIsProcessing(false); // Tắt loading
      setAiPrompt('');
    }
  };

  const scrollTimeline = (direction: 'left' | 'right') => {
    const container = document.getElementById('timeline-scroll');
    if (container) {
      const scrollAmount = 400;
      const newPosition = direction === 'left' 
        ? Math.max(0, scrollPosition - scrollAmount)
        : scrollPosition + scrollAmount;
      container.scrollTo({ left: newPosition, behavior: 'smooth' });
      setScrollPosition(newPosition);
    }
  };

  return (
    <div className="fixed inset-0 bg-black/70 backdrop-blur-sm z-[150] flex items-center justify-center p-4 pt-20">
      <div className="bg-white dark:bg-gray-800 rounded-3xl shadow-2xl w-full max-w-6xl max-h-[80vh] flex flex-col overflow-hidden transition-colors duration-300">
        
        {/* Header */}
        <div className="bg-gradient-to-r from-blue-600 to-purple-600 dark:from-blue-700 dark:to-purple-800 p-4 text-white flex-shrink-0">
          <div className="flex items-center justify-between mb-2">
            <div className="flex items-center gap-2">
              <div className="bg-white/20 backdrop-blur-sm p-1.5 rounded-lg">
                <Sparkles className="w-5 h-5" />
              </div>
              <div>
                <h2 className="text-xl">AI Trip Planner</h2>
                <p className="text-xs opacity-90">Personalized itinerary for your group</p>
              </div>
            </div>
            <button
              onClick={onClose}
              className="p-1.5 hover:bg-white/20 rounded-lg transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>

          {/* Stats */}
          <div className="grid grid-cols-4 gap-3 mt-3">
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-2">
              <div className="flex items-center gap-1.5 mb-0.5">
                <Clock className="w-3.5 h-3.5" />
                <span className="text-xs opacity-80">Duration</span>
              </div>
              <p className="text-base">9 hours</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-2">
              <div className="flex items-center gap-1.5 mb-0.5">
                <MapPin className="w-3.5 h-3.5" />
                <span className="text-xs opacity-80">Activities</span>
              </div>
              <p className="text-base">{activities.length} stops</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-2">
              <div className="flex items-center gap-1.5 mb-0.5">
                <DollarSign className="w-3.5 h-3.5" />
                <span className="text-xs opacity-80">Est. Cost</span>
              </div>
              <p className="text-base">520k VND</p>
            </div>
            <div className="bg-white/10 backdrop-blur-sm rounded-lg p-2">
              <div className="flex items-center gap-1.5 mb-0.5">
                <Users className="w-3.5 h-3.5" />
                <span className="text-xs opacity-80">Group Size</span>
              </div>
              <p className="text-base">4 people</p>
            </div>
          </div>
        </div>

        {/* Timeline */}
        <div className="relative flex-1 bg-gray-50 dark:bg-gray-900 p-4 overflow-y-auto">
          <div className="flex items-center justify-between mb-3">
            <h3 className="text-base dark:text-white">Suggested Itinerary</h3>
            <div className="flex gap-2">
              <button
                onClick={() => scrollTimeline('left')}
                className="p-1.5 bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md transition-all"
              >
                <ChevronLeft className="w-4 h-4 text-gray-600 dark:text-gray-400" />
              </button>
              <button
                onClick={() => scrollTimeline('right')}
                className="p-1.5 bg-white dark:bg-gray-800 rounded-lg shadow-sm hover:shadow-md transition-all"
              >
                <ChevronRight className="w-4 h-4 text-gray-600 dark:text-gray-400" />
              </button>
            </div>
          </div>

          {/* Horizontal Timeline */}
          <div 
            id="timeline-scroll"
            className="flex gap-4 overflow-x-auto pb-3 scroll-smooth hide-scrollbar"
            style={{ scrollbarWidth: 'none' }}
          >
            {activities.map((activity, index) => (
              <div key={activity.id} className="flex-shrink-0 w-72 relative">
                  {/* Timeline Connector */}
                  {index < activities.length - 1 && (
                    <div className="absolute top-1/2 -translate-y-1/2 left-full w-4 h-0.5 bg-gradient-to-r from-purple-400 to-blue-400 dark:from-purple-600 dark:to-blue-600 z-0" />
                  )}
                  
                  {/* Activity Card */}
                  <div 
                    className={`relative bg-white dark:bg-gray-800 rounded-xl shadow-lg hover:shadow-xl transition-all cursor-pointer border-2 ${
                      selectedActivity?.id === activity.id 
                        ? 'border-purple-500 ring-4 ring-purple-200 dark:ring-purple-900' 
                        : 'border-transparent'
                    } z-10`}
                    onClick={() => setSelectedActivity(activity)}
                  >
                    {/* Category Badge */}
                    <div className={`${categoryColors[activity.category]} px-3 py-1 rounded-t-xl text-white text-sm flex items-center justify-between`}>
                      <span>{categoryEmoji[activity.category]} {activity.category.toUpperCase()}</span>
                      <span>{activity.time}</span>
                    </div>

                    <div className="p-4">
                      <h4 className="text-lg mb-2 dark:text-white">{activity.title}</h4>
                      
                      <div className="space-y-2 mb-4 text-sm text-gray-600 dark:text-gray-400">
                        <div className="flex items-start gap-2">
                          <MapPin className="w-4 h-4 mt-0.5 flex-shrink-0" />
                          <span>{activity.location}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <Clock className="w-4 h-4 flex-shrink-0" />
                          <span>{activity.duration}</span>
                        </div>
                        <div className="flex items-center gap-2">
                          <DollarSign className="w-4 h-4 flex-shrink-0" />
                          <span>{activity.cost}</span>
                        </div>
                      </div>

                      <p className="text-sm text-gray-600 dark:text-gray-400 mb-4">
                        {activity.description}
                      </p>

                      {/* Action Buttons */}
                      <div className="flex gap-2">
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            handleRegenerateActivity(activity.id);
                          }}
                          className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-lg hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors text-sm"
                        >
                          <RefreshCw className="w-4 h-4" />
                          Regenerate
                        </button>
                        <button
                          onClick={(e) => {
                            e.stopPropagation();
                            setEditingId(activity.id);
                          }}
                          className="flex-1 flex items-center justify-center gap-2 px-3 py-2 bg-purple-100 dark:bg-purple-900/30 text-purple-700 dark:text-purple-400 rounded-lg hover:bg-purple-200 dark:hover:bg-purple-900/50 transition-colors text-sm"
                        >
                          <Edit2 className="w-4 h-4" />
                          Edit
                        </button>
                      </div>

                      {/* Feedback */}
                      <div className="flex gap-2 mt-3 pt-3 border-t border-gray-200 dark:border-gray-700">
                        <button className="flex-1 flex items-center justify-center gap-1 py-1.5 text-green-600 dark:text-green-400 hover:bg-green-50 dark:hover:bg-green-900/20 rounded transition-colors">
                          <ThumbsUp className="w-3.5 h-3.5" />
                          <span className="text-xs">Like</span>
                        </button>
                        <button className="flex-1 flex items-center justify-center gap-1 py-1.5 text-red-600 dark:text-red-400 hover:bg-red-50 dark:hover:bg-red-900/20 rounded transition-colors">
                          <ThumbsDown className="w-3.5 h-3.5" />
                          <span className="text-xs">Dislike</span>
                        </button>
                      </div>
                    </div>
                  </div>
              </div>
            ))}
          </div>
        </div>

        {/* AI Chat Input */}
        {showAIInput && (
          <div className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4 transition-all duration-300">
            <div className="max-w-4xl mx-auto">
              <div className="flex gap-3">
                <div className="flex-1 relative">
                  <input
                    type="text"
                    placeholder="Ask AI to modify the itinerary: 'Tìm quán phở rồi đi cafe'..."
                    value={aiPrompt}
                    onChange={(e) => setAiPrompt(e.target.value)}
                    onKeyDown={(e) => e.key === 'Enter' && handleSendPrompt()} // Đổi onKeyPress thành onKeyDown cho chuẩn
                    className="w-full px-4 py-3 bg-gray-100 dark:bg-gray-700 border border-gray-200 dark:border-gray-600 rounded-xl focus:outline-none focus:ring-2 focus:ring-purple-600 dark:text-white transition-colors"
                    disabled={isProcessing}
                  />
                </div>
                <button
                  onClick={handleSendPrompt}
                  disabled={!aiPrompt.trim() || isProcessing}
                  className="px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl hover:shadow-lg transition-all disabled:opacity-50 disabled:cursor-not-allowed flex items-center gap-2"
                >
                  {isProcessing ? <RefreshCw className="w-5 h-5 animate-spin" /> : <Send className="w-5 h-5" />}
                  {isProcessing ? 'Thinking...' : 'Send'}
                </button>
              </div>

              {/* Quick Suggestions */}
              <div className="flex flex-wrap gap-2 mt-3">
                <button onClick={() => setAiPrompt("Tìm quán ăn rẻ cho sinh viên")} className="px-3 py-1.5 text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                  💰 Tìm quán ăn rẻ
                </button>
                <button onClick={() => setAiPrompt("Tìm quán phở ngon")} className="px-3 py-1.5 text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                  🍜 Tìm quán phở
                </button>
                <button onClick={() => setAiPrompt("Đi xem phim rồi đi dạo")} className="px-3 py-1.5 text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                  🏛️ Đi chơi giải trí
                </button>
                <button onClick={() => setAiPrompt("Tìm khách sạn gần đây")} className="px-3 py-1.5 text-xs bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-full hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors">
                  ⚡ Tìm chỗ nghỉ
                </button>
              </div>
            </div>
          </div>
        )}

        {/* Toggle Edge */}
        <div className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700">
          <div className="flex justify-center">
            <button
              onClick={() => setShowAIInput(!showAIInput)}
              className="px-6 py-2 bg-gradient-to-r from-blue-600 to-purple-600 text-white hover:from-blue-700 hover:to-purple-700 transition-all flex items-center gap-2 rounded-b-lg shadow-lg"
            >
              {showAIInput ? (
                <>
                  <ChevronDown className="w-4 h-4" />
                  <span className="text-sm">Hide AI Chat</span>
                </>
              ) : (
                <>
                  <ChevronUp className="w-4 h-4" />
                  <span className="text-sm">Show AI Chat</span>
                  <Sparkles className="w-4 h-4" />
                </>
              )}
            </button>
          </div>
        </div>

        {/* Footer Actions */}
        <div className="bg-white dark:bg-gray-800 border-t border-gray-200 dark:border-gray-700 p-4">
          <div className="flex gap-3 max-w-4xl mx-auto">
            <button
              onClick={onClose}
              className="flex-1 px-6 py-3 bg-gray-100 dark:bg-gray-700 text-gray-700 dark:text-gray-300 rounded-xl hover:bg-gray-200 dark:hover:bg-gray-600 transition-colors"
            >
              Cancel
            </button>
            <button
              onClick={handleAcceptAll}
              className="flex-1 px-6 py-3 bg-gradient-to-r from-blue-600 to-purple-600 text-white rounded-xl hover:shadow-lg transition-all flex items-center justify-center gap-2"
            >
              <Check className="w-5 h-5" />
              Accept & Add to Planner
            </button>
          </div>
        </div>
      </div>

      <style>{`
        .hide-scrollbar::-webkit-scrollbar {
          display: none;
        }
      `}</style>
    </div>
  );
}